[package]
name = "libbladerf-sys"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"
links = "bladeRF"
build = "build.rs"

[dependencies]
bitfield = "0.13"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[build-dependencies]
bindgen = "0.53"
